project:
  type: website

website:
  title: "My Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/vidursaigal
      - icon: twitter
        href: https://x.com/vidur_saigal
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


